# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline.
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: detect-private-key # detects the presence of private keys.
    -   id: fix-byte-order-marker # removes utf-8 byte order marker.
    -   id: mixed-line-ending # replaces or checks mixed line ending.
    -   id: check-shebang-scripts-are-executable # ensures that (non-binary) files with a shebang are executable.
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
# -   repo: https://github.com/PyCQA/bandit
#     rev: 1.7.4
#     hooks:
#       - id: bandit
